spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/plan
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect